#ifndef MOS6502_ISA_H
#define MOS6502_ISA_H

#include <stdint.h>

typedef enum {
    INSTRUCTION_INVALID = 0,
    INSTRUCTION_ADD_WITH_CARRY,
    INSTRUCTION_BITWISE_AND,
    INSTRUCTION_ARITHMETIC_SHIFT_LEFT,
    INSTRUCTION_BRANCH_IF_CARRY_CLEAR,
    INSTRUCTION_BRANCH_IF_CARRY_SET,
    INSTRUCTION_BRANCH_IF_EQUAL,
    INSTRUCTION_BIT_TEST,
    INSTRUCTION_BRANCH_IF_MINUS,
    INSTRUCTION_BRANCH_IF_NOT_EQUAL,
    INSTRUCTION_BRANCH_IF_POSITIVE,
    INSTRUCTION_FORCE_BREAK,
    INSTRUCTION_BRANCH_IF_OVERFLOW_CLEAR,
    INSTRUCTION_BRANCH_IF_OVERFLOW_SET,
    INSTRUCTION_CLEAR_CARRY_FLAG,
    INSTRUCTION_CLEAR_DECIMAL_FLAG,
    INSTRUCTION_CLEAR_INTERRUPT_DISABLE,
    INSTRUCTION_CLEAR_OVERFLOW_FLAG,
    INSTRUCTION_COMPARE_ACCUMULATOR,
    INSTRUCTION_COMPARE_INDEX_X,
    INSTRUCTION_COMPARE_INDEX_Y,
    INSTRUCTION_DECREMENT_MEMORY,
    INSTRUCTION_DECREMENT_INDEX_X,
    INSTRUCTION_DECREMENT_INDEX_Y,
    INSTRUCTION_BITWISE_EXCLUSIVE_OR,
    INSTRUCTION_INCREMENT_MEMORY,
    INSTRUCTION_INCREMENT_INDEX_X,
    INSTRUCTION_INCREMENT_INDEX_Y,
    INSTRUCTION_JUMP,
    INSTRUCTION_JUMP_TO_SUBROUTINE,
    INSTRUCTION_LOAD_ACCUMULATOR,
    INSTRUCTION_LOAD_INDEX_X,
    INSTRUCTION_LOAD_INDEX_Y,
    INSTRUCTION_LOGICAL_SHIFT_RIGHT,
    INSTRUCTION_NO_OPERATION,
    INSTRUCTION_BITWISE_OR,
    INSTRUCTION_PUSH_ACCUMULATOR,
    INSTRUCTION_PUSH_PROCESSOR_STATUS,
    INSTRUCTION_PULL_ACCUMULATOR,
    INSTRUCTION_PULL_PROCESSOR_STATUS,
    INSTRUCTION_ROTATE_LEFT,
    INSTRUCTION_ROTATE_RIGHT,
    INSTRUCTION_RETURN_FROM_INTERRUPT,
    INSTRUCTION_RETURN_FROM_SUBROUTINE,
    INSTRUCTION_SUBTRACT_WITH_BORROW,
    INSTRUCTION_SET_CARRY_FLAG,
    INSTRUCTION_SET_DECIMAL_FLAG,
    INSTRUCTION_SET_INTERRUPT_DISABLE,
    INSTRUCTION_STORE_ACCUMULATOR,
    INSTRUCTION_STORE_INDEX_X,
    INSTRUCTION_STORE_INDEX_Y,
    INSTRUCTION_TRANSFER_ACCUMULATOR_TO_INDEX_X,
    INSTRUCTION_TRANSFER_ACCUMULATOR_TO_INDEX_Y,
    INSTRUCTION_TRANSFER_STACK_POINTER_TO_INDEX_X,
    INSTRUCTION_TRANSFER_INDEX_X_TO_ACCUMULATOR,
    INSTRUCTION_TRANSFER_INDEX_X_TO_STACK_POINTER,
    INSTRUCTION_TRANSFER_INDEX_Y_TO_ACCUMULATOR
} instruction_type_t;

static inline const char* instruction_type_to_string(const instruction_type_t type) {
    switch (type) {
        case INSTRUCTION_INVALID: return "INSTRUCTION_INVALID";
        case INSTRUCTION_ADD_WITH_CARRY: return "INSTRUCTION_ADD_WITH_CARRY";
        case INSTRUCTION_BITWISE_AND: return "INSTRUCTION_BITWISE_AND";
        case INSTRUCTION_ARITHMETIC_SHIFT_LEFT: return "INSTRUCTION_ARITHMETIC_SHIFT_LEFT";
        case INSTRUCTION_BRANCH_IF_CARRY_CLEAR: return "INSTRUCTION_BRANCH_IF_CARRY_CLEAR";
        case INSTRUCTION_BRANCH_IF_CARRY_SET: return "INSTRUCTION_BRANCH_IF_CARRY_SET";
        case INSTRUCTION_BRANCH_IF_EQUAL: return "INSTRUCTION_BRANCH_IF_EQUAL";
        case INSTRUCTION_BIT_TEST: return "INSTRUCTION_BIT_TEST";
        case INSTRUCTION_BRANCH_IF_MINUS: return "INSTRUCTION_BRANCH_IF_MINUS";
        case INSTRUCTION_BRANCH_IF_NOT_EQUAL: return "INSTRUCTION_BRANCH_IF_NOT_EQUAL";
        case INSTRUCTION_BRANCH_IF_POSITIVE: return "INSTRUCTION_BRANCH_IF_POSITIVE";
        case INSTRUCTION_FORCE_BREAK: return "INSTRUCTION_FORCE_BREAK";
        case INSTRUCTION_BRANCH_IF_OVERFLOW_CLEAR: return "INSTRUCTION_BRANCH_IF_OVERFLOW_CLEAR";
        case INSTRUCTION_BRANCH_IF_OVERFLOW_SET: return "INSTRUCTION_BRANCH_IF_OVERFLOW_SET";
        case INSTRUCTION_CLEAR_CARRY_FLAG: return "INSTRUCTION_CLEAR_CARRY_FLAG";
        case INSTRUCTION_CLEAR_DECIMAL_FLAG: return "INSTRUCTION_CLEAR_DECIMAL_FLAG";
        case INSTRUCTION_CLEAR_INTERRUPT_DISABLE: return "INSTRUCTION_CLEAR_INTERRUPT_DISABLE";
        case INSTRUCTION_CLEAR_OVERFLOW_FLAG: return "INSTRUCTION_CLEAR_OVERFLOW_FLAG";
        case INSTRUCTION_COMPARE_ACCUMULATOR: return "INSTRUCTION_COMPARE_ACCUMULATOR";
        case INSTRUCTION_COMPARE_INDEX_X: return "INSTRUCTION_COMPARE_INDEX_X";
        case INSTRUCTION_COMPARE_INDEX_Y: return "INSTRUCTION_COMPARE_INDEX_Y";
        case INSTRUCTION_DECREMENT_MEMORY: return "INSTRUCTION_DECREMENT_MEMORY";
        case INSTRUCTION_DECREMENT_INDEX_X: return "INSTRUCTION_DECREMENT_INDEX_X";
        case INSTRUCTION_DECREMENT_INDEX_Y: return "INSTRUCTION_DECREMENT_INDEX_Y";
        case INSTRUCTION_BITWISE_EXCLUSIVE_OR: return "INSTRUCTION_BITWISE_EXCLUSIVE_OR";
        case INSTRUCTION_INCREMENT_MEMORY: return "INSTRUCTION_INCREMENT_MEMORY";
        case INSTRUCTION_INCREMENT_INDEX_X: return "INSTRUCTION_INCREMENT_INDEX_X";
        case INSTRUCTION_INCREMENT_INDEX_Y: return "INSTRUCTION_INCREMENT_INDEX_Y";
        case INSTRUCTION_JUMP: return "INSTRUCTION_JUMP";
        case INSTRUCTION_JUMP_TO_SUBROUTINE: return "INSTRUCTION_JUMP_TO_SUBROUTINE";
        case INSTRUCTION_LOAD_ACCUMULATOR: return "INSTRUCTION_LOAD_ACCUMULATOR";
        case INSTRUCTION_LOAD_INDEX_X: return "INSTRUCTION_LOAD_INDEX_X";
        case INSTRUCTION_LOAD_INDEX_Y: return "INSTRUCTION_LOAD_INDEX_Y";
        case INSTRUCTION_LOGICAL_SHIFT_RIGHT: return "INSTRUCTION_LOGICAL_SHIFT_RIGHT";
        case INSTRUCTION_NO_OPERATION: return "INSTRUCTION_NO_OPERATION";
        case INSTRUCTION_BITWISE_OR: return "INSTRUCTION_BITWISE_OR";
        case INSTRUCTION_PUSH_ACCUMULATOR: return "INSTRUCTION_PUSH_ACCUMULATOR";
        case INSTRUCTION_PUSH_PROCESSOR_STATUS: return "INSTRUCTION_PUSH_PROCESSOR_STATUS";
        case INSTRUCTION_PULL_ACCUMULATOR: return "INSTRUCTION_PULL_ACCUMULATOR";
        case INSTRUCTION_PULL_PROCESSOR_STATUS: return "INSTRUCTION_PULL_PROCESSOR_STATUS";
        case INSTRUCTION_ROTATE_LEFT: return "INSTRUCTION_ROTATE_LEFT";
        case INSTRUCTION_ROTATE_RIGHT: return "INSTRUCTION_ROTATE_RIGHT";
        case INSTRUCTION_RETURN_FROM_INTERRUPT: return "INSTRUCTION_RETURN_FROM_INTERRUPT";
        case INSTRUCTION_RETURN_FROM_SUBROUTINE: return "INSTRUCTION_RETURN_FROM_SUBROUTINE";
        case INSTRUCTION_SUBTRACT_WITH_BORROW: return "INSTRUCTION_SUBTRACT_WITH_BORROW";
        case INSTRUCTION_SET_CARRY_FLAG: return "INSTRUCTION_SET_CARRY_FLAG";
        case INSTRUCTION_SET_DECIMAL_FLAG: return "INSTRUCTION_SET_DECIMAL_FLAG";
        case INSTRUCTION_SET_INTERRUPT_DISABLE: return "INSTRUCTION_SET_INTERRUPT_DISABLE";
        case INSTRUCTION_STORE_ACCUMULATOR: return "INSTRUCTION_STORE_ACCUMULATOR";
        case INSTRUCTION_STORE_INDEX_X: return "INSTRUCTION_STORE_INDEX_X";
        case INSTRUCTION_STORE_INDEX_Y: return "INSTRUCTION_STORE_INDEX_Y";
        case INSTRUCTION_TRANSFER_ACCUMULATOR_TO_INDEX_X: return "INSTRUCTION_TRANSFER_ACCUMULATOR_TO_INDEX_X";
        case INSTRUCTION_TRANSFER_ACCUMULATOR_TO_INDEX_Y: return "INSTRUCTION_TRANSFER_ACCUMULATOR_TO_INDEX_Y";
        case INSTRUCTION_TRANSFER_STACK_POINTER_TO_INDEX_X: return "INSTRUCTION_TRANSFER_STACK_POINTER_TO_INDEX_X";
        case INSTRUCTION_TRANSFER_INDEX_X_TO_ACCUMULATOR: return "INSTRUCTION_TRANSFER_INDEX_X_TO_ACCUMULATOR";
        case INSTRUCTION_TRANSFER_INDEX_X_TO_STACK_POINTER: return "INSTRUCTION_TRANSFER_INDEX_X_TO_STACK_POINTER";
        case INSTRUCTION_TRANSFER_INDEX_Y_TO_ACCUMULATOR: return "INSTRUCTION_TRANSFER_INDEX_Y_TO_ACCUMULATOR";
    }

    return "INSTRUCTION_UNKNOWN";
}

static const instruction_type_t instruction_type_by_opcode[256] = {
    [0x00] = INSTRUCTION_FORCE_BREAK,
    [0x01] = INSTRUCTION_BITWISE_OR, [0x05] = INSTRUCTION_BITWISE_OR,
    [0x09] = INSTRUCTION_BITWISE_OR, [0x0D] = INSTRUCTION_BITWISE_OR,
    [0x10] = INSTRUCTION_BRANCH_IF_POSITIVE, [0x11] = INSTRUCTION_BITWISE_OR,
    [0x15] = INSTRUCTION_BITWISE_OR, [0x18] = INSTRUCTION_CLEAR_CARRY_FLAG,
    [0x19] = INSTRUCTION_BITWISE_OR, [0x1D] = INSTRUCTION_BITWISE_OR,
    [0x20] = INSTRUCTION_JUMP_TO_SUBROUTINE, [0x21] = INSTRUCTION_BITWISE_AND,
    [0x24] = INSTRUCTION_BIT_TEST, [0x25] = INSTRUCTION_BITWISE_AND,
    [0x26] = INSTRUCTION_ROTATE_LEFT, [0x28] = INSTRUCTION_PULL_PROCESSOR_STATUS,
    [0x29] = INSTRUCTION_BITWISE_AND, [0x2A] = INSTRUCTION_ROTATE_LEFT,
    [0x2C] = INSTRUCTION_BIT_TEST, [0x2D] = INSTRUCTION_BITWISE_AND,
    [0x2E] = INSTRUCTION_ROTATE_LEFT,
    [0x30] = INSTRUCTION_BRANCH_IF_MINUS, [0x31] = INSTRUCTION_BITWISE_AND,
    [0x35] = INSTRUCTION_BITWISE_AND, [0x36] = INSTRUCTION_ROTATE_LEFT,
    [0x38] = INSTRUCTION_SET_CARRY_FLAG, [0x39] = INSTRUCTION_BITWISE_AND,
    [0x3D] = INSTRUCTION_BITWISE_AND, [0x3E] = INSTRUCTION_ROTATE_LEFT,
    [0x40] = INSTRUCTION_RETURN_FROM_INTERRUPT,
    [0x41] = INSTRUCTION_BITWISE_EXCLUSIVE_OR, [0x45] = INSTRUCTION_BITWISE_EXCLUSIVE_OR,
    [0x46] = INSTRUCTION_LOGICAL_SHIFT_RIGHT,
    [0x48] = INSTRUCTION_PUSH_ACCUMULATOR, [0x49] = INSTRUCTION_BITWISE_EXCLUSIVE_OR,
    [0x4A] = INSTRUCTION_LOGICAL_SHIFT_RIGHT, [0x4C] = INSTRUCTION_JUMP,
    [0x4D] = INSTRUCTION_BITWISE_EXCLUSIVE_OR, [0x4E] = INSTRUCTION_LOGICAL_SHIFT_RIGHT,
    [0x50] = INSTRUCTION_BRANCH_IF_OVERFLOW_CLEAR, [0x51] = INSTRUCTION_BITWISE_EXCLUSIVE_OR,
    [0x55] = INSTRUCTION_BITWISE_EXCLUSIVE_OR, [0x56] = INSTRUCTION_LOGICAL_SHIFT_RIGHT,
    [0x58] = INSTRUCTION_CLEAR_INTERRUPT_DISABLE, [0x59] = INSTRUCTION_BITWISE_EXCLUSIVE_OR,
    [0x5D] = INSTRUCTION_BITWISE_EXCLUSIVE_OR, [0x5E] = INSTRUCTION_LOGICAL_SHIFT_RIGHT,
    [0x60] = INSTRUCTION_RETURN_FROM_SUBROUTINE, [0x61] = INSTRUCTION_ADD_WITH_CARRY,
    [0x65] = INSTRUCTION_ADD_WITH_CARRY, [0x66] = INSTRUCTION_ROTATE_RIGHT,
    [0x68] = INSTRUCTION_PULL_ACCUMULATOR, [0x69] = INSTRUCTION_ADD_WITH_CARRY,
    [0x6A] = INSTRUCTION_ROTATE_RIGHT, [0x6C] = INSTRUCTION_JUMP,
    [0x6D] = INSTRUCTION_ADD_WITH_CARRY, [0x6E] = INSTRUCTION_ROTATE_RIGHT,
    [0x70] = INSTRUCTION_BRANCH_IF_OVERFLOW_SET, [0x71] = INSTRUCTION_ADD_WITH_CARRY,
    [0x75] = INSTRUCTION_ADD_WITH_CARRY, [0x76] = INSTRUCTION_ROTATE_RIGHT,
    [0x78] = INSTRUCTION_SET_INTERRUPT_DISABLE, [0x79] = INSTRUCTION_ADD_WITH_CARRY,
    [0x7D] = INSTRUCTION_ADD_WITH_CARRY, [0x7E] = INSTRUCTION_ROTATE_RIGHT,
    [0x81] = INSTRUCTION_STORE_ACCUMULATOR, [0x84] = INSTRUCTION_STORE_INDEX_Y,
    [0x85] = INSTRUCTION_STORE_ACCUMULATOR, [0x86] = INSTRUCTION_STORE_INDEX_X,
    [0x88] = INSTRUCTION_DECREMENT_INDEX_Y, [0x8A] = INSTRUCTION_TRANSFER_INDEX_X_TO_ACCUMULATOR,
    [0x8C] = INSTRUCTION_STORE_INDEX_Y, [0x8D] = INSTRUCTION_STORE_ACCUMULATOR,
    [0x8E] = INSTRUCTION_STORE_INDEX_X,
    [0x90] = INSTRUCTION_BRANCH_IF_CARRY_CLEAR, [0x91] = INSTRUCTION_STORE_ACCUMULATOR,
    [0x94] = INSTRUCTION_STORE_INDEX_Y, [0x95] = INSTRUCTION_STORE_ACCUMULATOR,
    [0x96] = INSTRUCTION_STORE_INDEX_X, [0x98] = INSTRUCTION_TRANSFER_INDEX_Y_TO_ACCUMULATOR,
    [0x99] = INSTRUCTION_STORE_ACCUMULATOR, [0x9A] = INSTRUCTION_TRANSFER_INDEX_X_TO_STACK_POINTER,
    [0x9D] = INSTRUCTION_STORE_ACCUMULATOR,
    [0xA0] = INSTRUCTION_LOAD_INDEX_Y, [0xA1] = INSTRUCTION_LOAD_ACCUMULATOR,
    [0xA2] = INSTRUCTION_LOAD_INDEX_X, [0xA4] = INSTRUCTION_LOAD_INDEX_Y,
    [0xA5] = INSTRUCTION_LOAD_ACCUMULATOR, [0xA6] = INSTRUCTION_LOAD_INDEX_X,
    [0xA8] = INSTRUCTION_TRANSFER_ACCUMULATOR_TO_INDEX_Y, [0xA9] = INSTRUCTION_LOAD_ACCUMULATOR,
    [0xAA] = INSTRUCTION_TRANSFER_ACCUMULATOR_TO_INDEX_X, [0xAC] = INSTRUCTION_LOAD_INDEX_Y,
    [0xAD] = INSTRUCTION_LOAD_ACCUMULATOR, [0xAE] = INSTRUCTION_LOAD_INDEX_X,
    [0xB0] = INSTRUCTION_BRANCH_IF_CARRY_SET, [0xB1] = INSTRUCTION_LOAD_ACCUMULATOR,
    [0xB4] = INSTRUCTION_LOAD_INDEX_Y, [0xB5] = INSTRUCTION_LOAD_ACCUMULATOR,
    [0xB6] = INSTRUCTION_LOAD_INDEX_X, [0xB8] = INSTRUCTION_CLEAR_OVERFLOW_FLAG,
    [0xB9] = INSTRUCTION_LOAD_ACCUMULATOR, [0xBA] = INSTRUCTION_TRANSFER_STACK_POINTER_TO_INDEX_X,
    [0xBC] = INSTRUCTION_LOAD_INDEX_Y, [0xBD] = INSTRUCTION_LOAD_ACCUMULATOR,
    [0xBE] = INSTRUCTION_LOAD_INDEX_X,
    [0xC0] = INSTRUCTION_COMPARE_INDEX_Y, [0xC1] = INSTRUCTION_COMPARE_ACCUMULATOR,
    [0xC4] = INSTRUCTION_COMPARE_INDEX_Y, [0xC5] = INSTRUCTION_COMPARE_ACCUMULATOR,
    [0xC6] = INSTRUCTION_DECREMENT_MEMORY, [0xC8] = INSTRUCTION_INCREMENT_INDEX_Y,
    [0xC9] = INSTRUCTION_COMPARE_ACCUMULATOR, [0xCA] = INSTRUCTION_DECREMENT_INDEX_X,
    [0xCC] = INSTRUCTION_COMPARE_INDEX_Y, [0xCD] = INSTRUCTION_COMPARE_ACCUMULATOR,
    [0xCE] = INSTRUCTION_DECREMENT_MEMORY,
    [0xD0] = INSTRUCTION_BRANCH_IF_NOT_EQUAL, [0xD1] = INSTRUCTION_COMPARE_ACCUMULATOR,
    [0xD5] = INSTRUCTION_COMPARE_ACCUMULATOR, [0xD6] = INSTRUCTION_DECREMENT_MEMORY,
    [0xD8] = INSTRUCTION_CLEAR_DECIMAL_FLAG, [0xD9] = INSTRUCTION_COMPARE_ACCUMULATOR,
    [0xDD] = INSTRUCTION_COMPARE_ACCUMULATOR, [0xDE] = INSTRUCTION_DECREMENT_MEMORY,
    [0xE0] = INSTRUCTION_COMPARE_INDEX_X, [0xE1] = INSTRUCTION_SUBTRACT_WITH_BORROW,
    [0xE4] = INSTRUCTION_COMPARE_INDEX_X, [0xE5] = INSTRUCTION_SUBTRACT_WITH_BORROW,
    [0xE6] = INSTRUCTION_INCREMENT_MEMORY, [0xE8] = INSTRUCTION_INCREMENT_INDEX_X,
    [0xE9] = INSTRUCTION_SUBTRACT_WITH_BORROW, [0xEA] = INSTRUCTION_NO_OPERATION,
    [0xEC] = INSTRUCTION_COMPARE_INDEX_X, [0xED] = INSTRUCTION_SUBTRACT_WITH_BORROW,
    [0xEE] = INSTRUCTION_INCREMENT_MEMORY,
    [0xF0] = INSTRUCTION_BRANCH_IF_EQUAL, [0xF1] = INSTRUCTION_SUBTRACT_WITH_BORROW,
    [0xF5] = INSTRUCTION_SUBTRACT_WITH_BORROW, [0xF6] = INSTRUCTION_INCREMENT_MEMORY,
    [0xF8] = INSTRUCTION_SET_DECIMAL_FLAG, [0xF9] = INSTRUCTION_SUBTRACT_WITH_BORROW,
    [0xFD] = INSTRUCTION_SUBTRACT_WITH_BORROW, [0xFE] = INSTRUCTION_INCREMENT_MEMORY,
};

static const uint8_t instruction_length[256] = {
    [0x00] = 1, [0xEA] = 1,
    [0xA9] = 2, [0xAD] = 3, [0xBD] = 3, [0xB9] = 3, [0xA5] = 2, [0xB5] = 2, [0xA1] = 2, [0xB1] = 2,
    [0xA2] = 2, [0xAE] = 3, [0xBE] = 3, [0xA6] = 2, [0xB6] = 2,
    [0xA0] = 2, [0xAC] = 3, [0xBC] = 3, [0xA4] = 2, [0xB4] = 2,
    [0x8D] = 3, [0x9D] = 3, [0x99] = 3, [0x85] = 2, [0x95] = 2, [0x81] = 2, [0x91] = 2,
    [0x8E] = 3, [0x86] = 2, [0x96] = 2,
    [0x8C] = 3, [0x84] = 2, [0x94] = 2,
    [0xAA] = 1, [0xA8] = 1, [0xBA] = 1, [0x8A] = 1, [0x98] = 1, [0x9A] = 1,
    [0x48] = 1, [0x08] = 1, [0x68] = 1, [0x28] = 1,
    [0x0A] = 1, [0x0E] = 3, [0x1E] = 3, [0x06] = 2, [0x16] = 2,
    [0x4A] = 1, [0x4E] = 3, [0x5E] = 3, [0x46] = 2, [0x56] = 2,
    [0x2A] = 1, [0x2E] = 3, [0x3E] = 3, [0x26] = 2, [0x36] = 2,
    [0x6A] = 1, [0x6E] = 3, [0x7E] = 3, [0x66] = 2, [0x76] = 2,
    [0x29] = 2, [0x2D] = 3, [0x3D] = 3, [0x39] = 3, [0x25] = 2, [0x35] = 2, [0x21] = 2, [0x31] = 2,
    [0x2C] = 3, [0x24] = 2,
    [0x49] = 2, [0x4D] = 3, [0x5D] = 3, [0x59] = 3, [0x45] = 2, [0x55] = 2, [0x41] = 2, [0x51] = 2,
    [0x09] = 2, [0x0D] = 3, [0x1D] = 3, [0x19] = 3, [0x05] = 2, [0x15] = 2, [0x01] = 2, [0x11] = 2,
    [0x69] = 2, [0x6D] = 3, [0x7D] = 3, [0x79] = 3, [0x65] = 2, [0x75] = 2, [0x61] = 2, [0x71] = 2,
    [0xC9] = 2, [0xCD] = 3, [0xDD] = 3, [0xD9] = 3, [0xC5] = 2, [0xD5] = 2, [0xC1] = 2, [0xD1] = 2,
    [0xE0] = 2, [0xEC] = 3, [0xE4] = 2,
    [0xC0] = 2, [0xCC] = 3, [0xC4] = 2,
    [0xE9] = 2, [0xED] = 3, [0xFD] = 3, [0xF9] = 3, [0xE5] = 2, [0xF5] = 2, [0xE1] = 2, [0xF1] = 2,
    [0xCE] = 3, [0xDE] = 3, [0xC6] = 2, [0xD6] = 2, [0xCA] = 1, [0x88] = 1,
    [0xEE] = 3, [0xFE] = 3, [0xE6] = 2, [0xF6] = 2, [0xE8] = 1, [0xC8] = 1,
    [0x4C] = 3, [0x6C] = 3, [0x20] = 3,
    [0x40] = 1, [0x60] = 1,
    [0x90] = 2, [0xB0] = 2, [0xF0] = 2, [0x30] = 2, [0xD0] = 2, [0x10] = 2, [0x50] = 2, [0x70] = 2,
    [0x18] = 1, [0xD8] = 1, [0x58] = 1, [0xB8] = 1, [0x38] = 1, [0xF8] = 1, [0x78] = 1,
};

static const uint8_t valid_opcode[256] = {
    [0x00] = 1, [0xEA] = 1,
    [0xA9] = 1, [0xAD] = 1, [0xBD] = 1, [0xB9] = 1, [0xA5] = 1, [0xB5] = 1, [0xA1] = 1, [0xB1] = 1,
    [0xA2] = 1, [0xAE] = 1, [0xBE] = 1, [0xA6] = 1, [0xB6] = 1,
    [0xA0] = 1, [0xAC] = 1, [0xBC] = 1, [0xA4] = 1, [0xB4] = 1,
    [0x8D] = 1, [0x9D] = 1, [0x99] = 1, [0x85] = 1, [0x95] = 1, [0x81] = 1, [0x91] = 1,
    [0x8E] = 1, [0x86] = 1, [0x96] = 1,
    [0x8C] = 1, [0x84] = 1, [0x94] = 1,
    [0xAA] = 1, [0xA8] = 1, [0xBA] = 1, [0x8A] = 1, [0x98] = 1, [0x9A] = 1,
    [0x48] = 1, [0x08] = 1, [0x68] = 1, [0x28] = 1,
    [0x0A] = 1, [0x0E] = 1, [0x1E] = 1, [0x06] = 1, [0x16] = 1,
    [0x4A] = 1, [0x4E] = 1, [0x5E] = 1, [0x46] = 1, [0x56] = 1,
    [0x2A] = 1, [0x2E] = 1, [0x3E] = 1, [0x26] = 1, [0x36] = 1,
    [0x6A] = 1, [0x6E] = 1, [0x7E] = 1, [0x66] = 1, [0x76] = 1,
    [0x29] = 1, [0x2D] = 1, [0x3D] = 1, [0x39] = 1, [0x25] = 1, [0x35] = 1, [0x21] = 1, [0x31] = 1,
    [0x2C] = 1, [0x24] = 1,
    [0x49] = 1, [0x4D] = 1, [0x5D] = 1, [0x59] = 1, [0x45] = 1, [0x55] = 1, [0x41] = 1, [0x51] = 1,
    [0x09] = 1, [0x0D] = 1, [0x1D] = 1, [0x19] = 1, [0x05] = 1, [0x15] = 1, [0x01] = 1, [0x11] = 1,
    [0x69] = 1, [0x6D] = 1, [0x7D] = 1, [0x79] = 1, [0x65] = 1, [0x75] = 1, [0x61] = 1, [0x71] = 1,
    [0xC9] = 1, [0xCD] = 1, [0xDD] = 1, [0xD9] = 1, [0xC5] = 1, [0xD5] = 1, [0xC1] = 1, [0xD1] = 1,
    [0xE0] = 1, [0xEC] = 1, [0xE4] = 1,
    [0xC0] = 1, [0xCC] = 1, [0xC4] = 1,
    [0xE9] = 1, [0xED] = 1, [0xFD] = 1, [0xF9] = 1, [0xE5] = 1, [0xF5] = 1, [0xE1] = 1, [0xF1] = 1,
    [0xCE] = 1, [0xDE] = 1, [0xC6] = 1, [0xD6] = 1, [0xCA] = 1, [0x88] = 1,
    [0xEE] = 1, [0xFE] = 1, [0xE6] = 1, [0xF6] = 1, [0xE8] = 1, [0xC8] = 1,
    [0x4C] = 1, [0x6C] = 1, [0x20] = 1,
    [0x40] = 1, [0x60] = 1,
    [0x90] = 1, [0xB0] = 1, [0xF0] = 1, [0x30] = 1, [0xD0] = 1, [0x10] = 1, [0x50] = 1, [0x70] = 1,
    [0x18] = 1, [0xD8] = 1, [0x58] = 1, [0xB8] = 1, [0x38] = 1, [0xF8] = 1, [0x78] = 1,
};

#endif
