//
// Created by chinmay on 08/04/26.
//

#ifndef MOS6502_ISA_H
#define MOS6502_ISA_H

typedef enum {
    INSTRUCTION_LOAD,
    INSTRUCTION_STORE,
    INSTRUCTION_MOVE,
    INSTRUCTION_ADD,
    INSTRUCTION_AND,
    INSTRUCTION_OR,
    INSTRUCTION_XOR,
    INSTRUCTION_TEST,
    INSTRUCTION_CMP,
    INSTRUCTION_JUMP_EQUAL,
    INSTRUCTION_JUMP_NOT_EQUAL,
    INSTRUCTION_JUMP,
    INSTRUCTION_CALL
} instruction_type_t;

#endif //MOS6502_ISA_H